In [1]:
import torch

# Tensor basics

#### torch.empty() creates tensor with any data type you want, torch.Tensor() only creates tensors of type torch.FloatTensor. So torch.Tensor() is a special case of torch.empty()

In [10]:
##creating empty tensor
a=torch.empty(1)   #scaler
print('a:',a)
b=torch.empty(3)   #1-D
print('b:',b)
c=torch.empty(2,2)  #2-D
print('c:',c)
d=torch.empty(2,3,2) #3-D
print('d:',d)
print('tpye of empty tensor:', d.dtype)

a: tensor([-1.7806e+27])
b: tensor([-1.7806e+27,  4.5698e-41, -2.9059e+07])
c: tensor([[-1.7806e+27,  4.5698e-41],
        [-2.9109e+07,  3.0733e-41]])
d: tensor([[[-1.7806e+27,  4.5698e-41],
         [-2.9119e+07,  3.0733e-41],
         [ 1.4013e-45,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]]])
tpye of empty tensor: torch.float32


In [9]:
##creating tensor with random values
a=torch.rand(1)   #scaler
print('a:',a)
b=torch.rand(3)   #1-D
print('b:',b)
c=torch.rand(2,2)  #2-D
print('c:',c)
d=torch.rand(2,3,2) #3-D
print('d:',d)
print('tpye of rand tensor:', d.dtype)

a: tensor([0.7403])
b: tensor([0.4947, 0.9709, 0.4873])
c: tensor([[0.5341, 0.2587],
        [0.4076, 0.8059]])
d: tensor([[[0.0275, 0.5968],
         [0.7773, 0.7455],
         [0.3259, 0.2409]],

        [[0.6497, 0.7031],
         [0.7782, 0.6036],
         [0.4873, 0.3317]]])
tpye of rand tensor: torch.float32


In [4]:
## torch with zeros and ones
a=torch.zeros(1)   #scaler
print('a:',a)
b=torch.zeros(3)   #1-D
print('b:',b)
c=torch.zeros(2,2)  #2-D
print('c:',c)
d=torch.zeros(2,3,2) #3-D
print('d:',d)

e=torch.ones(1)   #scaler
print('e:',e)
f=torch.ones(3)   #1-D
print('f:',f)
g=torch.ones(2,2)  #2-D
print('g:',g)
h=torch.ones(2,3,2) #3-D
print('h:',h)

a: tensor([0.])
b: tensor([0., 0., 0.])
c: tensor([[0., 0.],
        [0., 0.]])
d: tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])
e: tensor([1.])
f: tensor([1., 1., 1.])
g: tensor([[1., 1.],
        [1., 1.]])
h: tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])


In [16]:
print(a.dtype)

torch.float32


In [27]:
##changing data type
b=torch.ones(2,2, dtype=torch.int)   #1-D
print('b:',b)
c=torch.ones(2,2, dtype=torch.float16)   #1-D
print('c:',c)
d=torch.ones(2,2, dtype=torch.int16)   #1-D
print('d:',d)

b: tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
c: tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)
d: tensor([[1, 1],
        [1, 1]], dtype=torch.int16)


In [29]:
##size of tensor
b=torch.ones(2,2, dtype=torch.int)   #1-D
print('b:',b)
print('size of b:', b.size())
print('size of b',b.shape)

b: tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
size of b: torch.Size([2, 2])
size of b torch.Size([2, 2])


In [25]:
##another way of creating a tensor

a=torch.tensor([1.21,12,3])
print(a)

tensor([ 1.2100, 12.0000,  3.0000])


In [7]:
##operation on tensors
x=torch.rand(2,2)
y=torch.rand(2,2)
print('x:',x)
print('y:',y)

a=x+y
a=torch.add(x,y)
print('a',a)

b=x-y
a=torch.sub(x,y)
print('b:',b)

c=x*y
a=torch.mul(x,y)
print('c:',c)

d=x/y
a=torch.div(x,y)
print('d:',d)

x: tensor([[0.3676, 0.4455],
        [0.4191, 0.4266]])
y: tensor([[0.0511, 0.8247],
        [0.0444, 0.7447]])
a tensor([[0.4187, 1.2702],
        [0.4635, 1.1713]])
b: tensor([[ 0.3165, -0.3792],
        [ 0.3746, -0.3181]])
c: tensor([[0.0188, 0.3674],
        [0.0186, 0.3177]])
d: tensor([[7.1987, 0.5402],
        [9.4289, 0.5729]])


In [8]:
x=torch.rand(5,3)
print(x)
print('first row     :',x[0,:])
print('first column  :',x[:,0])
print('first two row :',x[0:2,:])
print('first two columns :',x[:,0:2])
print('last row:',x[-1,:])
print('last column:',x[:,-1])

#printing specific value from tensor
a=x[0,0]
print(a)
b=x[2,2]
print(b)

#printing actual value from tensor(item only availabe for scaler values)
print(x[0,0].item())
print(x[2,2].item())

tensor([[0.8442, 0.5387, 0.9402],
        [0.7159, 0.9412, 0.7024],
        [0.5917, 0.5546, 0.9049],
        [0.5859, 0.2922, 0.0793],
        [0.9103, 0.8070, 0.2382]])
first row     : tensor([0.8442, 0.5387, 0.9402])
first column  : tensor([0.8442, 0.7159, 0.5917, 0.5859, 0.9103])
first two row : tensor([[0.8442, 0.5387, 0.9402],
        [0.7159, 0.9412, 0.7024]])
first two columns : tensor([[0.8442, 0.5387],
        [0.7159, 0.9412],
        [0.5917, 0.5546],
        [0.5859, 0.2922],
        [0.9103, 0.8070]])
last row: tensor([0.9103, 0.8070, 0.2382])
last column: tensor([0.9402, 0.7024, 0.9049, 0.0793, 0.2382])
tensor(0.8442)
tensor(0.9049)
0.8441579341888428
0.904884397983551


In [9]:
##changing dimension of tensor
a=torch.rand(4,4)
print(a)
b=a.view(8,2)
print(b)
c=a.view(2,-1) ##after giving first dimension it will automatically detect 2 dimension
print(c)
d=a.view(16,-1) ##after giving first dimension it will automatically detect 2 dimension
print(d.T)

tensor([[0.0105, 0.3667, 0.0482, 0.9230],
        [0.7598, 0.0444, 0.4070, 0.5096],
        [0.3600, 0.0053, 0.2266, 0.7698],
        [0.3549, 0.6818, 0.3928, 0.6209]])
tensor([[0.0105, 0.3667],
        [0.0482, 0.9230],
        [0.7598, 0.0444],
        [0.4070, 0.5096],
        [0.3600, 0.0053],
        [0.2266, 0.7698],
        [0.3549, 0.6818],
        [0.3928, 0.6209]])
tensor([[0.0105, 0.3667, 0.0482, 0.9230, 0.7598, 0.0444, 0.4070, 0.5096],
        [0.3600, 0.0053, 0.2266, 0.7698, 0.3549, 0.6818, 0.3928, 0.6209]])
tensor([[0.0105, 0.3667, 0.0482, 0.9230, 0.7598, 0.0444, 0.4070, 0.5096, 0.3600,
         0.0053, 0.2266, 0.7698, 0.3549, 0.6818, 0.3928, 0.6209]])


In [62]:
x=torch.rand([4,256,100,100])
print(x.shape)
y=x.view(x.size(0),x.size(1),-1)
print(y.shape)
z=torch.mean(y,dim=2)
print(z.shape)
z1=torch.mean(x.view(x.shape[0],x.shape[1],-1),dim=2)
print(z1.shape)

torch.Size([4, 256, 100, 100])
torch.Size([4, 256, 10000])
torch.Size([4, 256])
torch.Size([4, 256])


In [ ]:
# converting tensor to numpy 
import numpy as np
a=torch.ones(5)
print(a)
print(type(a))
print('*'*20)
p=a.numpy()
print(p)
print(type(p))

In [69]:
a=torch.ones(2,2)
print(a)
b=a.numpy()
print(b)

tensor([[1., 1.],
        [1., 1.]])
[[1. 1.]
 [1. 1.]]


In [12]:
#numpy to tensor
a=np.ones(5)
print(a)
print(type(a))
print('*'*20)
b=torch.from_numpy(a)
print(b)
print(type(b))
###NOTE:-the tensor can be converted to numpy only if device is cpu not on gpu

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
********************
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>


# Checking GPU Status

In [70]:
###cheching whether GPU is avalable or not
torch.cuda.is_available()

False

In [3]:
import torch
import numpy

if torch.cuda.is_available():
    device=torch.device("cuda")
else:
    device=torch.device("cpu")
    x=torch.ones(5,device=device)
    print(x)
    y=torch.rand(5)
    print(y)
    y=y.to(device)

    z=x+y
    
    print(z)
    

tensor([1., 1., 1., 1., 1.])
tensor([0.4963, 0.3218, 0.1832, 0.1560, 0.6700])
tensor([1.4963, 1.3218, 1.1832, 1.1560, 1.6700])


# Gradient Calculation

In [4]:
###Gradient Calculations
x=torch.rand(3,requires_grad=True)
print(x)
y=x+2
z=y*y*2
z=z.mean()
print(z)
z.backward() ### means z(scaler) is the error or difference and we have to find grad of z w.r.t x
#(When we call .backward() on z, autograd calculates these gradients and stores them in the respective tensors’ .grad attribute.)
print(x.grad)   ######dz/dx


tensor([0.9666, 0.2050, 0.3420], requires_grad=True)
tensor(12.7650, grad_fn=<MeanBackward0>)
tensor([3.9554, 2.9400, 3.1226])


In [124]:
x=torch.rand(3,requires_grad=True)
print(x)
y=x+2
z=y*y*2
#z=z.mean()
print(z)
u=torch.tensor([1.0,0.2,0.3],dtype=torch.float32)
z.backward(u) ### jacobioan (dz/du)
print(x.grad)   ######dz/dx


tensor([0.5575, 0.2967, 0.0163], requires_grad=True)
tensor([13.0815, 10.5500,  8.1308], grad_fn=<MulBackward0>)
tensor([10.2300,  1.8374,  2.4195])


# To stop a tensor tracking the gradient
## 1. x.require_grad_(false)
## 2. x.detach()
## 3. with torch.no_grad()

In [25]:
x=torch.rand(3,requires_grad=True)
print(x)
x.requires_grad_(False)
print(x)


tensor([0.6579, 0.6068, 0.9234], requires_grad=True)
tensor([0.6579, 0.6068, 0.9234])


In [26]:
y=torch.rand(4,requires_grad=True)
print(y)
y=y.detach()
print(y)


tensor([0.4569, 0.2485, 0.2689, 0.7756], requires_grad=True)
tensor([0.4569, 0.2485, 0.2689, 0.7756])


In [29]:
x=torch.rand(3,requires_grad=True)
print(x)
with torch.no_grad():
    y=x+2
print(y)    

tensor([0.3078, 0.1705, 0.4481], requires_grad=True)
tensor([2.3078, 2.1705, 2.4481])


# weight.zero.grad_()

In [54]:
# Without zero.grad_()
weights=torch.ones(4,requires_grad=True)
for epoch in range(3):
    out=(weights*3).sum()
    #print(out)
    out.backward()
    print(weights.grad)


tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [53]:
# With zero.grad_()
weights=torch.ones(4,requires_grad=True)
for epoch in range(3):
    out=(weights*3).sum()
    #print(out)
    out.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


# Back Propagation

In [129]:
###Back propagation
x=torch.tensor([1.0])
y=torch.tensor([2.0])
w=torch.tensor([1.0],requires_grad=True)
y_hat=x*w
d=y_hat-y
loss=d**2
##backward propagation
loss.backward() ##error
print(w.grad) ##dl/dw=(dl/dd)*(dd/dy_hat)*dy_hat/dw

tensor([-2.])


# Gradient Descent

In [95]:
#####Gradientdescent_manually
import numpy as np 

# Compute every step manually

# Linear regression
# f = w * x 

# here : f = 2 * x
X = np.array([1, 2, 3, 4], dtype=np.float32)
Y = np.array([2, 4, 6, 8], dtype=np.float32)

w = 0.0

# model output
def forward(x):
    return w * x

# loss = MSE
def loss(y, y_pred):
    return ((y_pred - y)**2).mean()

# J = MSE = 1/N * (w*x - y)**2
# dJ/dw = 1/N * 2x(w*x - y)
def gradient(x, y, y_pred):
    return np.dot(2*x, y_pred - y).mean()

print(f'Prediction before training: f(5) = {forward(5):.3f}')

# Training
learning_rate = 0.01
n_iters = 20

for epoch in range(n_iters):
    # predict = forward pass
    y_pred = forward(X)

    # loss
    l = loss(Y, y_pred)
    
    # calculate gradients
    dw = gradient(X, Y, y_pred)

    # update weights
    w -= learning_rate * dw

    if epoch % 2 == 0:
        print(f'epoch={epoch+1}, w = {w:.3f}, loss = {l:.8f}')
     
print(f'Prediction after training: f(5) = {forward(5):.3f}')

Prediction before training: f(5) = 0.000
epoch=1, w = 1.200, loss = 30.00000000
epoch=3, w = 1.872, loss = 0.76800019
epoch=5, w = 1.980, loss = 0.01966083
epoch=7, w = 1.997, loss = 0.00050332
epoch=9, w = 1.999, loss = 0.00001288
epoch=11, w = 2.000, loss = 0.00000033
epoch=13, w = 2.000, loss = 0.00000001
epoch=15, w = 2.000, loss = 0.00000000
epoch=17, w = 2.000, loss = 0.00000000
epoch=19, w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000


In [164]:
###gradientdescent_auto

x=torch.tensor([1,2,3,4],dtype=torch.float32)
y=torch.tensor([2,4,6,8],dtype=torch.float32)
w=torch.tensor([0.0],requires_grad=True)

def forward(x):
    return w*x
def loss(y,y_pred):
    return ((y-y_pred)**2).mean()
lr=0.1
epochs=100
for epoch in range(epochs):
    y_pred=forward(x)
    l=loss(y,y_pred)
    l.backward()

    # update weights
    #w.data = w.data - learning_rate * w.grad
    with torch.no_grad():
        w -= learning_rate * w.grad
    
    # zero the gradients after updating
    w.grad.zero_()

    if epoch % 10== 0:
        print(f'epoch {epoch+1}: w = {w.item():.3f}, loss = {l.item():.8f}')

print(f'Prediction after training: f(5) = {forward(5).item():.3f}')
    



epoch 1: w = 0.300, loss = 30.00000000
epoch 11: w = 1.665, loss = 1.16278565
epoch 21: w = 1.934, loss = 0.04506890
epoch 31: w = 1.987, loss = 0.00174685
epoch 41: w = 1.997, loss = 0.00006770
epoch 51: w = 1.999, loss = 0.00000262
epoch 61: w = 2.000, loss = 0.00000010
epoch 71: w = 2.000, loss = 0.00000000
epoch 81: w = 2.000, loss = 0.00000000
epoch 91: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000


# Training Pipeline: Model, Loss, and Optimizer

In [168]:
###Training Pipeline: Model, Loss, and Optimizer
import torch.nn as nn
x=torch.tensor([1,2,3,4],dtype=torch.float32)
y=torch.tensor([2,4,6,8],dtype=torch.float32)
w=torch.tensor([0.0],requires_grad=True)

def forward(x):
    return w*x
lr=0.1
loss=nn.MSELoss()    ###using loss as predefined
optimizer=torch.optim.SGD([w],lr=lr)   ##optimizer

epochs=100
for epoch in range(epochs):
    y_pred=forward(x)
    l=loss(y,y_pred)
    l.backward()

    # update weights
    #w.data = w.data - learning_rate * w.grad
    optimizer.step()
    optimizer.zero_grad()

    if epoch % 10== 0:
        print(f'epoch {epoch+1}: w = {w.item():.3f}, loss = {l.item():.8f}')

print(f'Prediction after training: f(5) = {forward(5).item():.3f}')
    



epoch 1: w = 3.000, loss = 30.00000000
epoch 11: w = 2.001, loss = 0.00002861
epoch 21: w = 2.000, loss = 0.00000000
epoch 31: w = 2.000, loss = 0.00000000
epoch 41: w = 2.000, loss = 0.00000000
epoch 51: w = 2.000, loss = 0.00000000
epoch 61: w = 2.000, loss = 0.00000000
epoch 71: w = 2.000, loss = 0.00000000
epoch 81: w = 2.000, loss = 0.00000000
epoch 91: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000


In [108]:
import torch.nn as nn
x=torch.tensor([[1],[2],[3],[4]],dtype=torch.float32)
y=torch.tensor([[2],[4],[6],[8]],dtype=torch.float32)
x_test=torch.tensor([5],dtype=torch.float32)
#print(x.shape)
n_samples,n_features=x.shape[0],x.shape[1]
print(n_samples,n_features)
input_size=n_features
output_size=n_features

model=nn.Linear(input_size,output_size)
loss=nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=0.1)

n_epochs=100
for epoch in range(n_epochs):
    output=model(x)
    #print(output)
    #print(output.shape)
    l=loss(y,output)
    #print(l.item())
    l.backward()
    optimizer.step()
    optimizer.zero_grad()
    if epoch%10==0:
        [w, b] = model.parameters()
        print(f"epochs:{epoch+1}, loss:{l.item():3f}")
print(f'Prediction after training = {model(x_test).item():.3f}')

4 1
epochs:1, loss:54.546833
epochs:11, loss:0.065913
epochs:21, loss:0.026023
epochs:31, loss:0.014166
epochs:41, loss:0.007713
epochs:51, loss:0.004200
epochs:61, loss:0.002287
epochs:71, loss:0.001245
epochs:81, loss:0.000678
epochs:91, loss:0.000369
Prediction after training = 9.976


In [113]:
import torch.nn as nn
x=torch.tensor([[1],[2],[3],[4]],dtype=torch.float32)
y=torch.tensor([[2],[4],[6],[8]],dtype=torch.float32)
x_test=torch.tensor([5],dtype=torch.float32)
#print(x.shape)
n_samples,n_features=x.shape[0],x.shape[1]
print(n_samples,n_features)
input_size=n_features
output_size=n_features

class LinearReg(nn.Module):
    def __init__(self):
        super(LinearReg,self).__init__()
        
        self.Lin=nn.Linear(input_size,output_size)
    def forward(self,x):
        x=self.Lin(x)
        return x
model=LinearReg()   
loss=nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=0.1)

n_epochs=100
for epoch in range(n_epochs):
    output=model(x)
    #print(output)
    #print(output.shape)
    l=loss(y,output)
    #print(l.item())
    l.backward()
    optimizer.step()
    optimizer.zero_grad()
    if epoch%10==0:
        [w, b] = model.parameters()
        print(f"epochs:{epoch+1}, loss:{l.item():3f}")
print(f'Prediction after training = {model(x_test).item():.3f}')

4 1
epochs:1, loss:20.859375
epochs:11, loss:0.157385
epochs:21, loss:0.081965
epochs:31, loss:0.044627
epochs:41, loss:0.024298
epochs:51, loss:0.013230
epochs:61, loss:0.007203
epochs:71, loss:0.003922
epochs:81, loss:0.002135
epochs:91, loss:0.001163
Prediction after training = 9.957


# Data Loader

In [55]:
## Normal Folder wise
import torch
import glob
from torch.utils.data import DataLoader,Dataset
import PIL
from PIL import Image
import torchvision
from torchvision.transforms import Compose
from albumentations import *

class Train(Dataset):
    def __init__(self,path='/home/arvind/Videos/classification/test',augmentation=True,dim=(100,100)):
        self.dim=dim
        self.img_list=glob.glob('/home/arvind/Videos/classification/test/**/**')
        #self.label=[i.split('/')[-2] for i in self.img_list]
        self.dict={"building":0,"forest":1}
        self.augmentation=Compose([Rotate(limit = (1.,10.),p=0.5),Flip(0.5),
        RandomBrightnessContrast(brightness_limit=0.1, contrast_limit=0.1,p=0.2),
        #CLAHE(clip_limit=4.0, tile_grid_size=(8, 8), p=0.2),
        #GaussNoise(var_limit=(10.0, 50.0), mean=0, per_channel=True, always_apply=False, p=0.2)
        ],p=0.6)
    def augment(self,img):
        aug_img=self.augmentation(image=img)
        return aug_img['image'] 
        
    def __getitem__(self,index):
        img=self.img_list[index]
        labels=img.split('/')[-2]
        img=Image.open(img)
        img = img.resize(self.dim)
        img=np.asarray(img)/255
        
        if self.augmentation:
            img=self.augment(img)
        labels=self.dict[labels]
        return torch.FloatTensor(img.transpose(2,0,1)),torch.LongTensor([labels])
    def __len__(self):
        return len(self.img_list)

train=DataLoader(Train(path='/home/arvind/Videos/intel/train/**/**'),batch_size=4)
for image, label in train:
    print(image.shape)
    print(label.shape)
    break

In [192]:
### CSV 
import torch
from torch.utils.data import DataLoader, Dataset
import torchvision
from torchvision.transforms import Compose
import PIL
from PIL import Image
import pandas as pd
from albumentations import *
class Train(Dataset):
    def __init__(self,csv_path="/home/arvind/Videos/classification/testing.csv",augment=True,dim=(500,500),batch_size=4):
        self.batch_size=batch_size
        self.dim=dim
        self.df=pd.read_csv('/home/arvind/Videos/classification/testing.csv')
        self.image=self.df['path'].tolist()
        self.label=self.df['label'].tolist()
        self.dict={'forest':0,'building':1}
        self.aug=Compose([Rotate(limit = (1.,10.),p=0.5),Flip(0.5),
        RandomBrightnessContrast(brightness_limit=0.1, contrast_limit=0.1,p=0.2),],p=0.6)
    
    def augmentation(self,img):
        img=self.aug(image=img)
        return aug['image']
        
        
        
    def __getitem__(self,index):
        img=self.image[index]
        label=self.label[index]
        labels=self.dict[label]
        img=Image.open(img)
        img=img.resize(self.dim)
        img=np.asarray(img)
        if selg.augment:
            img=self.augmentation(img)
            
        return torch.FloatTensor(img.transpose(2,0,1)),torch.LongTensor([labels])
    def __len__(self):
        return len(self.image)
        
        
        
train=DataLoader(Train(csv_path="/home/arvind/Videos/classification/testing.csv",augment=True,dim=(100,100),batch_size=4))
for image,label in train:
    print(image.shape)
    print(labels.shape)
    break

In [49]:
# Segmentation DataLoader
import torch
from torch.utils.data import DataLoader, Dataset
import torchvision
from torchvision.transforms import transforms as T
from torchvision.transforms import Compose
from albumentations import *
import PIL
from PIL import Image
import cv2
import glob
from skimage.color import rgb2grey

class Train(Dataset):
    def __init__(self,img_path='/home/arvind/Videos/segmentation/Data/train',augmentation=True):
        self.augmentation=augmentation
        self.img=glob.glob('/home/arvind/Videos/segmentation/Data/train/image/**')
        self.label=glob.glob('/home/arvind/Videos/segmentation/Data/train/mask/**')
        self.aug = Compose([Rotate(limit = (5.,10.),p=0.5),OneOf([HorizontalFlip(p=0.5),VerticalFlip(p=0.5)]),
        RandomBrightnessContrast(p=0.5,brightness_limit=0.2,contrast_limit=0.2),HueSaturationValue(p=0.3)],p=0.5,additional_targets={'mask_full':'mask'})

    def augment(self,image,mask):
        aug_img=self.aug(image=image,mask=mask)
        return aug_img['image'],aug_img['mask']

    def __len__(self):
        return len(self.img)
    
    def __to_categorical__(self,mask):
        
        #Function to convert labels into categorical
        mask_bg = np.zeros((mask.shape[0],mask.shape[1]))
        mask_car = np.zeros((mask.shape[0],mask.shape[1]))
         
        mask_car[mask==1] = 1
        mask_bg[mask==0] = 1
        mask =np.concatenate((mask_bg[np.newaxis],mask_car[np.newaxis]),axis = 0)
        return mask.astype(np.float32)
    
    def make_class_label(self,label):
        
        label[label==1] = 255
        label[label==0] = 0
        return np.uint8(label)

    def __getitem__(self,index):
        images=self.img[index]
        #label=images.replace('/image/','/mask/')
        label=self.label[index]
        image=Image.open(images).convert('RGB')
        image=image.resize((572,572))
        image=np.asarray(image)
       

        
        label=Image.open(label).convert("RGB")
        label=label.resize((1024,1024))
        label=rgb2grey(np.asarray(label))
        label=self.make_class_label(label)
        
        if self.augmentation:
            image,label= self.augment(image,label)
        label = self.__to_categorical__(label)
        return torch.FloatTensor(image).permute(2,1,0),torch.FloatTensor(label)
        
train_loader= DataLoader(Train(), batch_size=4)

from tqdm import tqdm

for (imag1, labels) in train_loader:
    
    
    
    print(labels.shape)
    print(imag1.shape)
    break    

<ipython-input-49-106293712ba3>:58: FutureWarning: rgb2grey is deprecated. It will be removed in version 0.19.Please use rgb2gray instead.
  label=rgb2grey(np.asarray(label))


torch.Size([4, 2, 1024, 1024])
torch.Size([4, 3, 572, 572])


# Transforms in Data Loader

In [208]:
import torch
import glob
from torch.utils.data import DataLoader,Dataset
import PIL
from PIL import Image
import torchvision
from torchvision import transforms as t
from torchvision.transforms import Compose
from albumentations import *

class Train(Dataset):
    def __init__(self,path='/home/arvind/Videos/classification/test',augmentation=True,dim=(100,100),transform=None):
        self.dim=dim
        self.img_list=glob.glob('/home/arvind/Videos/classification/test/**/**')
        #self.label=[i.split('/')[-2] for i in self.img_list]
        self.dict={"building":0,"forest":1}
        self.augmentation=Compose([Rotate(limit = (1.,10.),p=0.5),Flip(0.5),
        RandomBrightnessContrast(brightness_limit=0.1, contrast_limit=0.1,p=0.2),
        #CLAHE(clip_limit=4.0, tile_grid_size=(8, 8), p=0.2),
        #GaussNoise(var_limit=(10.0, 50.0), mean=0, per_channel=True, always_apply=False, p=0.2)
        ],p=0.6)
        self.transform=transform
    def augment(self,img):
        aug_img=self.augmentation(image=img)
        return aug_img['image'] 
        
    def __getitem__(self,index):
        img=self.img_list[index]
        labels=img.split('/')[-2]
        img=Image.open(img)
        img = img.resize(self.dim)
        img=np.asarray(img)/255
        
        if self.augmentation:
            img=self.augment(img)
        if self.transform is not None:
            img=self.transform(img)
            
        labels=self.dict[labels]
        return torch.FloatTensor(img),torch.LongTensor([labels])
    def __len__(self):
        return len(self.img_list)
train_transform = t.Compose([t.ToTensor(),
                                t.Normalize((0.5, 0.5, 0.5), 
                                                     (0.5, 0.5, 0.5))])
train=DataLoader(Train(path='/home/arvind/Videos/classification/test/**',transform=train_transform),batch_size=4)


# Softmax and Cross-Entopy

In [30]:
#softmax
import numpy as np
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

x = np.array([2.0, 1.0, 2])
outputs = softmax(x)
print(outputs)

[0.4223188 0.1553624 0.4223188]


In [14]:
import torch
import torch.nn as nn
def cross_entropy(actual, predicted):
    return -np.sum(actual*np.log(predicted))
x=np.asarray([1,0,0,0])
y=np.asarray([0.7,0.1,0.1,0.1])
z=np.asarray([0.6,0.2,0.1,0.1]) ## loss will increase
loss1=cross_entropy(x,y)
loss2=cross_entropy(x,z)

print(f"loss1:{loss1:0.3f}")
print(f"loss2:{loss2:0.3f}")

loss1:0.357
loss2:0.511


In [28]:
import torch.nn as nn
loss = nn.CrossEntropyLoss()

Y = torch.tensor([0])
y1=torch.tensor([1])
print('value of y: ',Y)

Y_pred_good = torch.tensor([[2.0, 1.0, 0.1]])
_,pred1=torch.max(Y_pred_good,1)
print('pred 1: ',pred1)
Y_pred_bad = torch.tensor([[0.5, 2.0, 0.3]])
_,pred2=torch.max(Y_pred_bad,1)
print('pred 2: ',pred2)
l1 = loss(Y_pred_good, Y)
l2 = loss(Y_pred_bad, Y)
print(f'PyTorch Loss1: {l1.item():.4f}')
print(f'PyTorch Loss2: {l2.item():.4f}')

value of y:  tensor([0])
pred 1:  tensor([0])
pred 2:  tensor([1])
PyTorch Loss1: 0.4170
PyTorch Loss2: 1.8406


In [31]:
def cross_entropy(actual, predicted):
    return -np.sum(actual*np.log(predicted))
x=np.asarray([1,0,0])
y=np.asarray([2.0, 1.0, 0.1])
y=softmax(y)
loss1=cross_entropy(x,y)

print(f"loss1:{loss1:0.3f}")

loss1:0.417


In [36]:
### Loss for batch size of 4
Y = torch.tensor([2,0,1,0])

# input is of size nBatch x nClasses = 3 x 3
# Y_pred are logits (not softmax)
Y_pred_good = torch.tensor(
    [[0.1, 0.2, 3.9,0.6], # predict class 2
    [1.2, 0.1, 0.3,0.9], # predict class 0
    [0.3, 2.2, 0.2,2.3],
     [0.3, 2.2, 0.1,1.9]]) # predict class 1
pred1=torch.max(Y_pred_good,1)
print('pred1',pred1)

Y_pred_bad = torch.tensor(
    [[0.9, 0.2, 0.1,5.0],
    [0.1, 0.3, 1.5,2.0],
    [1.2, 0.2, 0.5,1.5],
    [0.3, 2.2, 0.2,1.5]])
pred2=torch.max(Y_pred_bad,1)
print('pred2',pred2)

l1 = loss(Y_pred_good, Y)
l2 = loss(Y_pred_bad, Y)
print(f'Batch Loss1:  {l1.item():.4f}')
print(f'Batch Loss2: {l2.item():.4f}')

pred1 torch.return_types.max(
values=tensor([3.9000, 1.2000, 2.3000, 2.2000]),
indices=tensor([2, 0, 3, 1]))
pred2 torch.return_types.max(
values=tensor([5.0000, 2.0000, 1.5000, 2.2000]),
indices=tensor([3, 3, 3, 1]))
Batch Loss1:  1.1150
Batch Loss2: 3.0347


# Models

In [40]:
#CNN model
import torch
import torch.nn as nn

class CNN(nn.Module):
    def __init__(self,n_class=4,n_channels=3):
        super(CNN,self).__init__()
        
        self.conv1=nn.Conv2d(in_channels=3,out_channels=12,kernel_size=3,stride=1,padding=1)
        self.pool1=nn.MaxPool2d(kernel_size=2)
        
        self.conv2=nn.Conv2d(in_channels=12,out_channels=24,kernel_size=3,stride=1,padding=1)
        self.pool2=nn.MaxPool2d(kernel_size=2)
        
        self.conv3=nn.Conv2d(in_channels=24,out_channels=32,kernel_size=3,stride=1,padding=1)
        self.pool3=nn.MaxPool2d(kernel_size=2)
        
        self.fc1=nn.Linear(in_features=32,out_features=256)
        self.fc2=nn.Linear(in_features=256,out_features=128)
        self.fc3=nn.Linear(in_features=128,out_features=4)
        
        
    def forward(self,x):
        x=self.conv1(x)
        #print(x.shape)
        x=self.pool1(x)
        #print(x.shape)
        
        x=self.conv2(x)
        #print(x.shape)
        x=self.pool2(x)
        #print(x.shape)
        
        x=self.conv3(x)
        #print(x.shape)
        x=self.pool3(x)
        #print('before flatting: ',x.shape)
        x=x.view(x.size(0),x.size(1),-1)
        #print('on doing flatting: ',x.shape)
        x=torch.mean(x,dim=2)
        #print('after calculating mean: ',x.shape)
        #print('flatting',x.shape)
        
        x=self.fc1(x)
        #print('after fc1',x.shape)
        x=self.fc2(x)
        #print('after fc2',x.shape)
        x=self.fc3(x)
        print('after fc3',x.shape)
        
        return x

model=CNN(n_class=4)
x=torch.randn(4,3,256,256)
model(x)

after fc3 torch.Size([4, 4])


tensor([[ 0.0003,  0.1476,  0.0313, -0.1012],
        [-0.0003,  0.1484,  0.0312, -0.1008],
        [ 0.0002,  0.1477,  0.0313, -0.1010],
        [ 0.0010,  0.1478,  0.0307, -0.1012]], grad_fn=<AddmmBackward>)

In [ ]:
###segmentation model
import torch
import torch.nn as nn
import torch
import torch.nn as nn

def double_conv(in_channels, out_channels):
    return nn.Sequential(
        nn.Conv2d(in_channels, out_channels, 3, padding=1),
        nn.ReLU(inplace=True),
        nn.Conv2d(out_channels, out_channels, 3, padding=1),
        nn.ReLU(inplace=True)
    )   


class UNet(nn.Module):

    def __init__(self, n_class):
        super().__init__()
                
        self.dconv_down1 = double_conv(3, 64)
        self.dconv_down2 = double_conv(64, 128)
        self.dconv_down3 = double_conv(128, 256)
        self.dconv_down4 = double_conv(256, 512)        

        self.maxpool = nn.MaxPool2d(2)
        self.upsample = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)        
        
        self.dconv_up3 = double_conv(256 + 512, 256)
        self.dconv_up2 = double_conv(128 + 256, 128)
        self.dconv_up1 = double_conv(128 + 64, 64)
        
        self.conv_last = nn.Conv2d(64, n_class, 1)
        
        
    def forward(self, x):
        conv1 = self.dconv_down1(x)
        x = self.maxpool(conv1)

        conv2 = self.dconv_down2(x)
        x = self.maxpool(conv2)
        
        conv3 = self.dconv_down3(x)
        x = self.maxpool(conv3)   
        
        x = self.dconv_down4(x)
        
        x = self.upsample(x)        
        x = torch.cat([x, conv3], dim=1)
        
        x = self.dconv_up3(x)
        x = self.upsample(x)        
        x = torch.cat([x, conv2], dim=1)       

        x = self.dconv_up2(x)
        x = self.upsample(x)        
        x = torch.cat([x, conv1], dim=1)   
        
        x = self.dconv_up1(x)
        print(x.shape)
        
        out = self.conv_last(x)
        
        return out

x=torch.randn(4,3,1024,1024)
model=UNet(n_class=4)
model(x) 

/home/arvind/anaconda3/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)


## Adaptive Avarage Pooling

In [4]:
import torch
import torch.nn as nn
m = nn.AdaptiveAvgPool2d((5,7))
input = torch.randn(1, 64, 8, 9)
output = m(input)
output.shape

torch.Size([1, 64, 5, 7])

In [14]:
def binary_cross_entropy(y_, y): 
    return -(y_.log()*y + (1-y)*(1-y_).log()).mean()

y=torch.rand([1,1,12,8])
y_=torch.rand([1,1,12,8])
loss = binary_cross_entropy(y_, y)
loss


tensor(1.2009)

# Attention Techniques

In [71]:
#spatial Attention
class attention_block(nn.Module):
    def __init__(self,in_ch,kernel_size=1,stride=1,dilation=1):
        super(attention_block,self).__init__()
        self.in_ch = in_ch
        self.conv1 = nn.Conv2d(in_ch, in_ch//2, kernel_size=kernel_size,stride=stride,bias=False,dilation=dilation)
            
            
        self.conv2= nn.Conv2d(in_ch//2, 1, kernel_size=kernel_size,stride=stride,bias=False,dilation=dilation)
            
            
        self.act = nn.Softmax(dim=1)
    def forward(self, x):
        x =self.conv1(x)
        print(x.shape)
        x=self.conv2 (x)
        print(x.shape)
       
       
        return x
        
x=torch.rand([4,32,100,100])
model=attention_block(in_ch=32)
model(x)

    

torch.Size([4, 16, 100, 100])
torch.Size([4, 1, 100, 100])


tensor([[[[ 0.1382,  0.0885,  0.2156,  ...,  0.2409,  0.1734,  0.1402],
          [ 0.1611,  0.1879,  0.0779,  ...,  0.1017,  0.1426,  0.1705],
          [ 0.2138,  0.1151,  0.2065,  ...,  0.0866,  0.0567,  0.2231],
          ...,
          [ 0.1446,  0.1508,  0.1730,  ...,  0.2398, -0.0120,  0.1381],
          [ 0.0363,  0.1807,  0.1683,  ..., -0.0241,  0.0316,  0.2043],
          [ 0.2821,  0.1444,  0.1310,  ...,  0.0134,  0.1966,  0.1532]]],


        [[[-0.0187,  0.0305,  0.1288,  ...,  0.2258,  0.1170,  0.2328],
          [ 0.0684,  0.1204,  0.1484,  ...,  0.1411,  0.1879,  0.2117],
          [ 0.2195,  0.1852,  0.0763,  ...,  0.1434,  0.1718, -0.0779],
          ...,
          [ 0.0514,  0.0251,  0.2610,  ...,  0.1701,  0.1108,  0.1688],
          [ 0.0590,  0.1551,  0.1032,  ...,  0.1173,  0.1498,  0.1180],
          [ 0.1084,  0.1637,  0.1118,  ...,  0.1246,  0.1552,  0.2572]]],


        [[[ 0.2159,  0.2421,  0.0720,  ...,  0.0543,  0.1283, -0.0170],
          [ 0.2517,  0.336

In [75]:
class attention_block(nn.Module):
    def __init__(self,in_ch,kernel_size=1,stride=1,dilation=1):
        super(attention_block,self).__init__()
        self.in_ch = in_ch
        print(self.in_ch)
        self.attn1 = nn.Sequential(
            nn.Conv2d(in_ch, in_ch//2, kernel_size=kernel_size,stride=stride,bias=False,dilation=dilation),
            nn.BatchNorm2d(in_ch//2),
            nn.ReLU(),
            nn.Conv2d(in_ch//2, 1, kernel_size=kernel_size,stride=stride,bias=False,dilation=dilation),
            nn.BatchNorm2d(1)
            )
        self.act = nn.Softmax(dim=1)
    def forward(self, x):
        print(x.shape)
        x1 = self.attn1(x)
        print(x1.shape)
        x1 = x1.div(math.sqrt(self.in_ch))
        x1 = self.act(x1)
        return x1 * x
    
x=torch.rand([4,32,100,100])
model=attention_block(in_ch=32)
model(x)

32
torch.Size([4, 32, 100, 100])
torch.Size([4, 1, 100, 100])


tensor([[[[0.0262, 0.0522, 0.8230,  ..., 0.4913, 0.2711, 0.6350],
          [0.3761, 0.1114, 0.9824,  ..., 0.4967, 0.9155, 0.7620],
          [0.3279, 0.3883, 0.3882,  ..., 0.7728, 0.0851, 0.4713],
          ...,
          [0.0270, 0.4382, 0.4280,  ..., 0.9941, 0.5767, 0.0607],
          [0.3417, 0.7304, 0.5603,  ..., 0.9621, 0.6954, 0.3495],
          [0.4599, 0.8446, 0.0960,  ..., 0.0275, 0.3741, 0.0995]],

         [[0.2884, 0.0569, 0.4078,  ..., 0.5882, 0.5662, 0.1987],
          [0.6087, 0.6621, 0.0903,  ..., 0.7807, 0.8314, 0.7223],
          [0.2364, 0.4533, 0.2001,  ..., 0.5693, 0.0633, 0.6276],
          ...,
          [0.9429, 0.6904, 0.8040,  ..., 0.7896, 0.4480, 0.2987],
          [0.9212, 0.9352, 0.7983,  ..., 0.1570, 0.0684, 0.0560],
          [0.9440, 0.2931, 0.1291,  ..., 0.1171, 0.1115, 0.6850]],

         [[0.4524, 0.6719, 0.1480,  ..., 0.5947, 0.7498, 0.6563],
          [0.8591, 0.5761, 0.7877,  ..., 0.6060, 0.0568, 0.7443],
          [0.7241, 0.9386, 0.6230,  ..., 0

In [77]:
x=torch.rand([4,32,100,100])
x1=torch.rand([4,1,100,100])
y=x1.div(math.sqrt(32))
y

tensor([[[[0.0525, 0.0979, 0.1569,  ..., 0.0582, 0.0247, 0.0160],
          [0.0727, 0.1608, 0.0610,  ..., 0.1571, 0.1218, 0.1418],
          [0.1507, 0.0386, 0.1734,  ..., 0.1465, 0.0286, 0.0477],
          ...,
          [0.1480, 0.1568, 0.0321,  ..., 0.0315, 0.0649, 0.0335],
          [0.1738, 0.0994, 0.0688,  ..., 0.0802, 0.0657, 0.0310],
          [0.0529, 0.0835, 0.1130,  ..., 0.1761, 0.1584, 0.0418]]],


        [[[0.1763, 0.0707, 0.1292,  ..., 0.0475, 0.1614, 0.0835],
          [0.0437, 0.0608, 0.0600,  ..., 0.1288, 0.1687, 0.0706],
          [0.1224, 0.1491, 0.0600,  ..., 0.1608, 0.0421, 0.1761],
          ...,
          [0.0551, 0.0708, 0.0202,  ..., 0.0822, 0.0533, 0.1279],
          [0.1265, 0.1765, 0.0488,  ..., 0.1384, 0.0031, 0.1202],
          [0.0876, 0.0008, 0.0861,  ..., 0.1241, 0.1249, 0.0756]]],


        [[[0.0253, 0.1442, 0.1468,  ..., 0.0377, 0.1401, 0.0757],
          [0.0853, 0.1156, 0.1075,  ..., 0.0927, 0.0535, 0.0732],
          [0.0816, 0.0781, 0.1404,  ..

In [29]:
x=torch.rand([4, 1, 100, 100])
x1=torch.rand([4, 100, 100, 100])
l=x1*x
print(l.shape)

torch.Size([4, 100, 100, 100])


In [34]:
x=torch.rand([3,100,100])
y=torch.mean(x,dim=2)
y=torch.mean(y,dim=1)

print(y.shape)
print(y)

torch.Size([3])
tensor([0.4996, 0.5009, 0.5044])


In [45]:
x=torch.tensor([1,4,9,16])
x1=torch.tensor([1,2,3,4])
y=x.div(x1)
print(y)

tensor([1., 2., 3., 4.])


In [11]:

import torch
import torch.nn as nn

class h_sigmoid(nn.Module):
    def __init__(self, inplace=True, h_max=1):
        super(h_sigmoid, self).__init__()
        self.relu = nn.ReLU6(inplace=inplace)
        self.h_max = h_max

    def forward(self, x):
        return self.relu(x + 3) * self.h_max / 6
    
class scale_attention_block(nn.Module): 
    def __init__(self,in_ch,kernel_size=1,stride=1,dilation=1):
        super(attention_block,self).__init__()
        self.in_ch = in_ch
        self.pool=nn.AvgPool2d(2)
        self.conv1 = nn.Conv2d(in_ch, in_ch//2, kernel_size=kernel_size,stride=stride,bias=False,dilation=dilation)
            
            
        self.conv2= nn.Conv2d(in_ch//2, 1, kernel_size=kernel_size,stride=stride,bias=False,dilation=dilation)
            
            
        self.relu=nn.ReLU()
        self.h_sigmoid=h_sigmoid()
    def forward(self, x):
        x=self.pool(x)
        x =self.conv1(x)
        print(x.shape)
        x=self.h_sigmoid((self.relu(self.conv2(x))))
        print(x.shape)
       
       
        return x
        
x=torch.rand([4,32,100,100])
model=attention_block(in_ch=32)
model(x)

    

torch.Size([4, 16, 50, 50])
torch.Size([4, 1, 50, 50])


tensor([[[[0.0000, 0.0000, 0.0000,  ..., 0.0761, 0.0557, 0.0000],
          [0.0754, 0.0228, 0.0540,  ..., 0.0000, 0.0423, 0.0297],
          [0.0134, 0.0000, 0.0666,  ..., 0.0000, 0.1152, 0.0134],
          ...,
          [0.0017, 0.0431, 0.0304,  ..., 0.0056, 0.0134, 0.0787],
          [0.0668, 0.0147, 0.0264,  ..., 0.0549, 0.0182, 0.0000],
          [0.0000, 0.0534, 0.0000,  ..., 0.0570, 0.0794, 0.0180]]],


        [[[0.0416, 0.0327, 0.0473,  ..., 0.0161, 0.0649, 0.0689],
          [0.0236, 0.0064, 0.0248,  ..., 0.0000, 0.0000, 0.0131],
          [0.0000, 0.0332, 0.0000,  ..., 0.0000, 0.0215, 0.0834],
          ...,
          [0.0556, 0.0366, 0.0503,  ..., 0.0465, 0.0120, 0.0710],
          [0.0284, 0.0265, 0.0335,  ..., 0.0000, 0.0463, 0.0489],
          [0.0000, 0.0000, 0.0087,  ..., 0.0000, 0.0097, 0.0000]]],


        [[[0.0045, 0.0000, 0.0334,  ..., 0.0878, 0.0000, 0.0459],
          [0.1276, 0.0626, 0.0277,  ..., 0.0323, 0.0000, 0.0000],
          [0.0136, 0.0749, 0.0000,  ..

In [ ]:
## channel Attention
class attention_block(nn.Module):
    def __init__(self,in_ch,kernel_size=1,stride=1,dilation=1):
        super(attention_block,self).__init__()
        self.in_ch = in_ch
        self.conv1 = nn.Conv2d(in_ch, in_ch//2, kernel_size=kernel_size,stride=stride,bias=False,dilation=dilation)
            
            
        self.conv2= nn.Conv2d(in_ch//2, 1, kernel_size=kernel_size,stride=stride,bias=False,dilation=dilation)
            
            
        self.act = nn.Softmax(dim=1)
    def forward(self, x):
        x =self.conv1(x)
        print(x.shape)
        x=self.conv2 (x)
        print(x.shape)
       
       
        return x
        
x=torch.rand([4,32,100,100])
model=attention_block(in_ch=32)
model(x)

    

In [2]:
### CBAM
import torch
import torch.nn as nn
class ChannelAttention(nn.Module):
    def __init__(self, in_planes, ratio=16):
        super(ChannelAttention, self).__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.max_pool = nn.AdaptiveMaxPool2d(1)
           
        self.fc = nn.Sequential(nn.Conv2d(in_planes, in_planes // 16, 1, bias=False),
                               nn.ReLU(),
                               nn.Conv2d(in_planes // 16, in_planes, 1, bias=False))
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg_out = self.fc(self.avg_pool(x))
        max_out = self.fc(self.max_pool(x))
        out = avg_out + max_out
        return self.sigmoid(out)
    
class SpatialAttention(nn.Module):
    def __init__(self, kernel_size=3):
        super(SpatialAttention, self).__init__()

        self.conv1 = nn.Conv2d(2, 1, kernel_size, padding=kernel_size//2, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg_out = torch.mean(x, dim=1, keepdim=True)
        max_out, _ = torch.max(x, dim=1, keepdim=True)
        x = torch.cat([avg_out, max_out], dim=1)
        x = self.conv1(x)
        return self.sigmoid(x)
    
x=torch.rand([4,32,2736,1824])
model=SpatialAttention(kernel_size=3)
model1=ChannelAttention(in_planes=32)
op=model1(x)*x
op=model(op)*op
print(op.shape)

torch.Size([4, 32, 2736, 1824])


# Loss Funtions

In [48]:
### Dice Loss
import torch
import torch.nn as nn
class weighted_dice_loss(nn.Module):
    def __init__(self, n_classes,weights = None):
        super(weighted_dice_loss, self).__init__()
        self.n_classes = n_classes
        self.weights = weights
    


    def forward(self, target, logit):
        # logit => N x Classes x H x W
        # target => N x H x W

        N = len(logit)
        #print(N)
        #print('target',target.dtype)
        #print('logit',logit.dtype)
        pred = torch.nn.functional.softmax(logit,dim=1)
        print('pred_shape',pred.shape)
        #print('pred',pred.dtype)
        #target = torch.LongTensor(target).detach().cpu()
        #target_onehot = self.to_one_hot(target, self.n_classes)

        # Numerator Product
        inter = 2*pred * target
        print('inter1 shape',inter.shape)
        # Sum over all pixels N x C x H x W => N x C
        inter = inter.view(N, self.n_classes, -1).sum(2)
        print('inter 2 shape',inter.shape)

        # Denominator
        union = pred + target 
        print('union',union.shape)
        # Sum over all pixels N x C x H x W => N x C
        union = union.view(N, self.n_classes, -1).sum(2)
        inter = inter * self.weights 
        union = union * self.weights
        loss = inter / (union + 1)
        print('loss',loss.mean())


        # Return average loss over classes and batch
        return 1-loss.mean()
weights = torch.FloatTensor([1.0,1.0,1.0,1.0])
dice_loss_train = weighted_dice_loss(4,weights=weights)   
x=torch.randn([4,4,100,100])
y=torch.randn([4,4,100,100])

loss2=  dice_loss_train(x,y)
loss2

pred_shape torch.Size([4, 4, 100, 100])
inter1 shape torch.Size([4, 4, 100, 100])
inter 2 shape torch.Size([4, 4])
union torch.Size([4, 4, 100, 100])
loss tensor(0.0021)


tensor(0.9979)

In [51]:
## dice loss simplified
class dice_loss(nn.Module):
    def __init__(self,n_class,weights):
        super(dice_loss,self).__init__()
        self.weights=weights
        self.n_class=n_class
        
    def forward(self,mask,output):
        pred=torch.nn.functional.softmax(output,dim=1)
        inter=2*mask*pred
        inter=inter.view(inter.shape[0],inter.shape[1],-1).sum(2)
        print(inter.shape)
        
        union=pred+mask
        union=union.view(union.shape[0],union.shape[1],-1).sum(2)
        print(union.shape)
        inter = inter * self.weights 
        union = union * self.weights
        loss=inter/(union+1)
        loss=1-loss.mean()
        print(loss)
        
        return loss
        
weights = torch.FloatTensor([1.0,1.0,1.0,1.0])
dice_loss_t = dice_loss(4,weights=weights)   
x=torch.randn([4,4,100,100])
y=torch.randn([4,4,100,100])

loss2=  dice_loss_t(x,y)


torch.Size([4, 4])
torch.Size([4, 4])
tensor(-0.0075)


In [7]:
x=torch.randn([4,4,100,100])
y=x.view(4,4,-1).sum(2)
print(y.shape)

torch.Size([4, 4])


In [49]:
x=torch.ones([1,4])
print(x)
y=torch.nn.functional.softmax(x)
print(y)

tensor([[1., 1., 1., 1.]])
tensor([[0.2500, 0.2500, 0.2500, 0.2500]])


<ipython-input-49-6fc7da1ccfe0>:3: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  y=torch.nn.functional.softmax(x)


In [105]:
# Negative log likelihood loss>>> To take log the probability value after softmax and add the probability value of the correct answer to the average
### formual>>>>>>>
m = nn.LogSoftmax(dim=1)

# input is of size N x C = 3 x 5
input = torch.randn(3,5, requires_grad=True)
target=torch.tensor([0,2,1])
print(input)
x=m(input)
print(x)
loss = nn.NLLLoss()
output = loss(x, target)
print(output)

tensor([[-0.3941, -1.4198, -2.1953, -0.8406,  0.1629],
        [ 1.2566,  1.4996, -0.4067,  0.3345, -0.4112],
        [ 2.1165,  0.3435, -0.7622, -1.0368, -0.2451]], requires_grad=True)
tensor([[-1.3633, -2.3890, -3.1645, -1.8098, -0.8063],
        [-1.1154, -0.8725, -2.7787, -2.0375, -2.7832],
        [-0.3097, -2.0827, -3.1883, -3.4630, -2.6713]],
       grad_fn=<LogSoftmaxBackward>)
tensor(2.0749, grad_fn=<NllLossBackward>)


In [89]:
### focal Loss
import torch.nn as nn
import torch.nn.functional as F
class FocalLoss(nn.Module):
    def __init__(self, gamma=3, weight=None):
        super(FocalLoss, self).__init__()
        self.gamma = gamma
        self.weight = weight
        self.reduction = True

    def forward(self, input,target):
        """
        input: [N, C], float32
        target: [N, ], int64
        """
        N = input.size(0)
        C = input.size(1)
        print(N)
        print(C)
        #input = input.permute(2,3,0,1)
        input = input.view(N,C,-1)
        print('input',input.shape)
        #print(input.size())
        
        _,target = target.max(dim=1)
        #print(target.size())
        target = target.view(N,-1)
        print('target',target.shape)
        print(target.size())
        logpt = F.log_softmax(input, dim=1)
        print('logpt',logpt.shape)
        pt = torch.exp(logpt)
        logpt = (1-pt)**self.gamma * logpt
        print('logpt-----',logpt.shape)
        loss = F.nll_loss(logpt, target, self.weight) #negative log likelihood loss
        return loss

weights = torch.FloatTensor([1.0,1.0,1.0,1.0])
focal_loss = FocalLoss(weight=weights).cuda()
x=torch.randn([4,4,100,100])
y=torch.randn([4,4,100,100])

loss=  focal_loss(x,y)
print(loss)

4
4
input torch.Size([4, 4, 10000])
target torch.Size([4, 10000])
torch.Size([4, 10000])
logpt torch.Size([4, 4, 10000])
logpt----- torch.Size([4, 4, 10000])
tensor(1.0837)


In [95]:
## focal loss simplified
class focal_loss(nn.Module):
    def __init__(self,weights,gamma=3):
        super(focal_loss,self).__init__()
        self.weights=weights
        self.gamma=gamma
        
    def forward(self,label,output):
        output=output.view(output.shape[0],output.shape[1],-1)
        print(output.shape)
        log=torch.nn.functional.log_softmax(output,dim=1)
        pt=torch.exp(log)
        logpt=(1-pt)**self.gamma*log
        
        _,label=label.max(dim=1)
        label=label.view(label.shape[0],-1)
        print(label.shape)
        
        loss = F.nll_loss(logpt, label, self.weights) #negative log likelihood loss
        return loss
    
        
        



        
weights = torch.FloatTensor([1.0,1.0,1.0,1.0])
focal_loss = focal_loss(weights=weights).cuda()
x=torch.randn([4,4,100,100])
y=torch.randn([4,4,100,100])
focal_loss(x,y)


torch.Size([4, 4, 10000])
torch.Size([4, 10000])


tensor(1.0957)

In [ ]:
## boundary loss
def one_hot(label, n_classes, requires_grad=True):
    """Return One Hot Label"""
    device = label.device
    one_hot_label = torch.eye(
        n_classes, device=device, requires_grad=requires_grad)[label]
    one_hot_label = one_hot_label.transpose(1, 3).transpose(2, 3)

    return one_hot_label

class BoundaryLoss(nn.Module):
    """Boundary Loss proposed in:
    Alexey Bokhovkin et al., Boundary Loss for Remote Sensing Imagery Semantic Segmentation
    https://arxiv.org/abs/1905.07852
    """

    def __init__(self, theta0=3, theta=5):
        super().__init__()

        self.theta0 = theta0
        self.theta = theta

    @staticmethod
    def to_one_hot(tensor, n_classes):
        #tensor = torch.FloatTensor(tensor)
        n, h, w = tensor.size()
        # print('N H W',n,h,w)
        zeros = torch.zeros(n, n_classes, h, w)
        #zeros = torch.cuda.FloatTensor(tensor.size(0),n_classes,tensor.size(1),tensor.size(2)).zero_()
        #view_tensor = tensor.view(n, 1, h, w)
        view_tensor = torch.reshape(tensor,(n,-1))
        #print("tensor reshape", tensor.dtype)
        ones = torch.ones(tensor.size())
        one_hot = zeros.scatter_(1, tensor, ones)
        return one_hot


    def forward(self, gt, pred):
        

        n, c, _, _ = pred.shape

        # softmax so that predicted map can be distributed in [0, 1]
        pred = torch.softmax(pred, dim=1)

        # one-hot vector of ground truth
        # gt = torch.LongTensor(gt).detach().cpu()
        # gt = torch.LongTensor(gt.long().detach().cpu())
        # one_hot_gt = self.to_one_hot(gt, c)
        one_hot_gt = gt

        # boundary map
        gt_b = F.max_pool2d(
            1 - one_hot_gt, kernel_size=self.theta0, stride=1, padding=(self.theta0 - 1) // 2)
        gt_b -= 1 - one_hot_gt

        pred_b = F.max_pool2d(
            1 - pred, kernel_size=self.theta0, stride=1, padding=(self.theta0 - 1) // 2)
        pred_b -= 1 - pred

        # extended boundary map
        gt_b_ext = F.max_pool2d(
            gt_b, kernel_size=self.theta, stride=1, padding=(self.theta - 1) // 2)

        pred_b_ext = F.max_pool2d(
            pred_b, kernel_size=self.theta, stride=1, padding=(self.theta - 1) // 2)

        # reshape
        gt_b = gt_b.view(n, c, -1)
        pred_b = pred_b.view(n, c, -1)
        gt_b_ext = gt_b_ext.view(n, c, -1)
        pred_b_ext = pred_b_ext.view(n, c, -1)

        # Precision, Recall
        P = torch.sum(pred_b * gt_b_ext, dim=2) / (torch.sum(pred_b, dim=2) + 1e-7)
        R = torch.sum(pred_b_ext * gt_b, dim=2) / (torch.sum(gt_b, dim=2) + 1e-7)

        # Boundary F1 Score
        BF1 = 2 * P * R / (P + R + 1e-7)

        # summing BF1 Score for each class and average over mini-batch
        loss = torch.mean(1 - BF1)

        return loss


In [104]:
import pandas as pd
df=pd.read_csv('/home/arvind/Documents/gauge_200_backtest_results/cumulative_grade_5jan_all_cls.csv')
df=df[['imei','manual_grade']]
df1=df.drop_duplicates(subset=['imei'])
df1.to_csv('/home/arvind/Documents/gauge_200_backtest_results/used_manual_grade_gauge_200.csv')

In [121]:
df=pd.read_csv('/home/arvind/Documents/20_apr_compare_front_pred/cumulative_grade_5jan_all_cls.csv')
#df.head()
df['front_grade_old']=df['front_grade']
df=df[['imei','asset_id','front_grade_old']]
df1=pd.read_csv('/home/arvind/Documents/20_apr_compare_front_pred/cummulative_all_side_sourabh_front_model.csv')
df1['front_grade_new']=df1['front_grade']
df1=df1[['imei','asset_id','front_grade_new']]
df2=df.merge(df1,on=['imei','asset_id'],how='left')
df2.to_csv('/home/arvind/Documents/20_apr_compare_front_pred/front_compared.csv')

In [128]:
df=pd.read_csv('/home/arvind/Documents/20_apr_compare_front_pred/front_compared.csv')
df1=pd.read_csv('/home/arvind/Documents/20_apr_compare_front_pred/cummulative_all_side_sourabh_front_model_1.csv')
df1['front_grade_new_1']=df1['front_grade']
df1=df1[['imei','asset_id','front_grade_new_1']]
df2=df.merge(df1,on=['imei','asset_id'],how='left')
df2.to_csv('/home/arvind/Documents/20_apr_compare_front_pred/front_compared.csv')

In [19]:
import pandas as pd
df=pd.read_excel('/home/arvind/Documents/gauge_200_backtest_results/3may_back_compared/cumulative_grade_5jan_all_cls.xlsx',sheet_name='cumulative_grade_5jan_all_cls')
#df.head()
df['back_grade_old']=df['back_grade']
df['pred_cumulative_grade_old']=df['pred_cumulative_grade']
df=df[['imei','asset_id','back_grade_old','pred_cumulative_grade_old']]
df1=pd.read_excel('/home/arvind/Documents/gauge_200_backtest_results/3may_back_compared/cummulative_all_side_sourabh_back_model_val_acc_2.xlsx',sheet_name='cummulative_all_side_sourabh_back_model')
df1['back_grade_new']=df1['back_grade']
df1['pred_cumulative_grade_new']=df1['pred_cumulative_grade']
df1=df1[['imei','asset_id','back_grade_new','pred_cumulative_grade_new','manual_grade']]
df2=df1.merge(df,on=['imei','asset_id'],how='left')
df2.to_csv('/home/arvind/Documents/gauge_200_backtest_results/3may_back_compared/back_compared.csv')